import { iso2ToFlag } from './utils';

import type { Country } from './types';

/**
 * Capital city by ISO 3166-1 alpha-2 country code.
 *
 * Sources: ISO 3166-1, UN M49 conventions, world-countries dataset.
 *
 * Notes on edge cases:
 *  - Bolivia: La Paz (administrative seat). Sucre is the constitutional capital.
 *  - Côte d'Ivoire: Yamoussoukro (official). Abidjan is the de facto economic capital.
 *  - South Africa: Pretoria (executive). Cape Town and Bloemfontein hold the other branches.
 *  - Sri Lanka: Sri Jayawardenepura Kotte (official). Colombo is the commercial capital.
 *  - Israel: Jerusalem (declared). Status is internationally disputed.
 *  - Palestine: Ramallah (administrative seat). East Jerusalem is the proclaimed capital.
 *  - Nauru: Yaren (de facto, no official capital).
 *  - Hong Kong / Macao / Singapore / Monaco / Vatican City / San Marino: city-states or
 *    territories where the capital equals the entity name.
 */
const CAPITALS: Record<string, string> = {
  af: 'Kabul',
  al: 'Tirana',
  dz: 'Algiers',
  ad: 'Andorra la Vella',
  ao: 'Luanda',
  ag: "St. John's",
  ar: 'Buenos Aires',
  am: 'Yerevan',
  au: 'Canberra',
  at: 'Vienna',
  az: 'Baku',
  bs: 'Nassau',
  bh: 'Manama',
  bd: 'Dhaka',
  bb: 'Bridgetown',
  by: 'Minsk',
  be: 'Brussels',
  bz: 'Belmopan',
  bj: 'Porto-Novo',
  bt: 'Thimphu',
  bo: 'La Paz',
  ba: 'Sarajevo',
  bw: 'Gaborone',
  br: 'Brasília',
  bn: 'Bandar Seri Begawan',
  bg: 'Sofia',
  bf: 'Ouagadougou',
  bi: 'Gitega',
  kh: 'Phnom Penh',
  cm: 'Yaoundé',
  ca: 'Ottawa',
  cv: 'Praia',
  cf: 'Bangui',
  td: "N'Djamena",
  cl: 'Santiago',
  cn: 'Beijing',
  co: 'Bogotá',
  km: 'Moroni',
  cg: 'Brazzaville',
  cd: 'Kinshasa',
  cr: 'San José',
  hr: 'Zagreb',
  ci: 'Yamoussoukro',
  cu: 'Havana',
  cy: 'Nicosia',
  cz: 'Prague',
  dk: 'Copenhagen',
  dj: 'Djibouti',
  dm: 'Roseau',
  do: 'Santo Domingo',
  ec: 'Quito',
  eg: 'Cairo',
  sv: 'San Salvador',
  gq: 'Malabo',
  er: 'Asmara',
  ee: 'Tallinn',
  sz: 'Mbabane',
  et: 'Addis Ababa',
  fj: 'Suva',
  fi: 'Helsinki',
  fr: 'Paris',
  ga: 'Libreville',
  gm: 'Banjul',
  ge: 'Tbilisi',
  de: 'Berlin',
  gh: 'Accra',
  gr: 'Athens',
  gd: "St. George's",
  gt: 'Guatemala City',
  gn: 'Conakry',
  gw: 'Bissau',
  gy: 'Georgetown',
  ht: 'Port-au-Prince',
  hn: 'Tegucigalpa',
  hk: 'Hong Kong',
  hu: 'Budapest',
  is: 'Reykjavík',
  in: 'New Delhi',
  id: 'Jakarta',
  ir: 'Tehran',
  iq: 'Baghdad',
  ie: 'Dublin',
  il: 'Jerusalem',
  it: 'Rome',
  jm: 'Kingston',
  jp: 'Tokyo',
  jo: 'Amman',
  kz: 'Astana',
  ke: 'Nairobi',
  ki: 'Tarawa',
  xk: 'Pristina',
  kw: 'Kuwait City',
  kg: 'Bishkek',
  la: 'Vientiane',
  lv: 'Riga',
  lb: 'Beirut',
  ls: 'Maseru',
  lr: 'Monrovia',
  ly: 'Tripoli',
  li: 'Vaduz',
  lt: 'Vilnius',
  lu: 'Luxembourg',
  mo: 'Macao',
  mg: 'Antananarivo',
  mw: 'Lilongwe',
  my: 'Kuala Lumpur',
  mv: 'Malé',
  ml: 'Bamako',
  mt: 'Valletta',
  mh: 'Majuro',
  mr: 'Nouakchott',
  mu: 'Port Louis',
  mx: 'Mexico City',
  fm: 'Palikir',
  md: 'Chișinău',
  mc: 'Monaco',
  mn: 'Ulaanbaatar',
  me: 'Podgorica',
  ma: 'Rabat',
  mz: 'Maputo',
  mm: 'Naypyidaw',
  na: 'Windhoek',
  nr: 'Yaren',
  np: 'Kathmandu',
  nl: 'Amsterdam',
  nz: 'Wellington',
  ni: 'Managua',
  ne: 'Niamey',
  ng: 'Abuja',
  kp: 'Pyongyang',
  mk: 'Skopje',
  no: 'Oslo',
  om: 'Muscat',
  pk: 'Islamabad',
  pw: 'Ngerulmud',
  ps: 'Ramallah',
  pa: 'Panama City',
  pg: 'Port Moresby',
  py: 'Asunción',
  pe: 'Lima',
  ph: 'Manila',
  pl: 'Warsaw',
  pt: 'Lisbon',
  pr: 'San Juan',
  qa: 'Doha',
  ro: 'Bucharest',
  ru: 'Moscow',
  rw: 'Kigali',
  kn: 'Basseterre',
  lc: 'Castries',
  vc: 'Kingstown',
  ws: 'Apia',
  sm: 'San Marino',
  st: 'São Tomé',
  sa: 'Riyadh',
  sn: 'Dakar',
  rs: 'Belgrade',
  sc: 'Victoria',
  sl: 'Freetown',
  sg: 'Singapore',
  sk: 'Bratislava',
  si: 'Ljubljana',
  sb: 'Honiara',
  so: 'Mogadishu',
  za: 'Pretoria',
  kr: 'Seoul',
  ss: 'Juba',
  es: 'Madrid',
  lk: 'Sri Jayawardenepura Kotte',
  sd: 'Khartoum',
  sr: 'Paramaribo',
  se: 'Stockholm',
  ch: 'Bern',
  sy: 'Damascus',
  tw: 'Taipei',
  tj: 'Dushanbe',
  tz: 'Dodoma',
  th: 'Bangkok',
  tl: 'Dili',
  tg: 'Lomé',
  to: "Nuku'alofa",
  tt: 'Port of Spain',
  tn: 'Tunis',
  tr: 'Ankara',
  tm: 'Ashgabat',
  tv: 'Funafuti',
  ug: 'Kampala',
  ua: 'Kyiv',
  ae: 'Abu Dhabi',
  gb: 'London',
  us: 'Washington, D.C.',
  uy: 'Montevideo',
  uz: 'Tashkent',
  vu: 'Port Vila',
  va: 'Vatican City',
  ve: 'Caracas',
  vn: 'Hanoi',
  ye: "Sana'a",
  zm: 'Lusaka',
  zw: 'Harare',
};

function c(
  name: string,
  iso2: string,
  iso3: string,
  dialCode: string,
  region: string,
  subregion: string,
  format?: string,
  priority: number = 0,
  areaCodes?: string[],
): Country {
  const capital = CAPITALS[iso2];
  if (!capital) {
    throw new Error(`Missing capital for country "${name}" (iso2="${iso2}")`);
  }
  return {
    name,
    iso2: iso2 as Country['iso2'],
    iso3,
    dialCode,
    format,
    priority,
    areaCodes,
    flag: iso2ToFlag(iso2),
    capital,
    region,
    subregion,
  };
}

/**
 * Complete list of countries with dial codes, formatting masks, and metadata.
 * Sorted alphabetically by name.
 *
 * Format masks use '.' as digit placeholder:
 *   "... ... ...." means 3 digits, space, 3 digits, space, 4 digits
 */
export const countries: Country[] = [
  c('Afghanistan', 'af', 'afg', '93', 'Asia', 'Southern Asia', '.. ... ....'),
  c('Albania', 'al', 'alb', '355', 'Europe', 'Southern Europe', '.. ... ....'),
  c('Algeria', 'dz', 'dza', '213', 'Africa', 'Northern Africa', '... .. .. ..'),
  c('Andorra', 'ad', 'and', '376', 'Europe', 'Southern Europe', '... ...'),
  c('Angola', 'ao', 'ago', '244', 'Africa', 'Middle Africa', '... ... ...'),
  c('Antigua and Barbuda', 'ag', 'atg', '1', 'Americas', 'Caribbean', '... ....', 2, ['268']),
  c('Argentina', 'ar', 'arg', '54', 'Americas', 'South America', '.. ........'),
  c('Armenia', 'am', 'arm', '374', 'Asia', 'Western Asia', '.. ......'),
  c('Australia', 'au', 'aus', '61', 'Oceania', 'Australia and New Zealand', '. .... ....'),
  c('Austria', 'at', 'aut', '43', 'Europe', 'Western Europe', '.... ......'),
  c('Azerbaijan', 'az', 'aze', '994', 'Asia', 'Western Asia', '.. ... .. ..'),
  c('Bahamas', 'bs', 'bhs', '1', 'Americas', 'Caribbean', '... ....', 2, ['242']),
  c('Bahrain', 'bh', 'bhr', '973', 'Asia', 'Western Asia', '.... ....'),
  c('Bangladesh', 'bd', 'bgd', '880', 'Asia', 'Southern Asia', '.... ......'),
  c('Barbados', 'bb', 'brb', '1', 'Americas', 'Caribbean', '... ....', 2, ['246']),
  c('Belarus', 'by', 'blr', '375', 'Europe', 'Eastern Europe', '.. ... .. ..'),
  c('Belgium', 'be', 'bel', '32', 'Europe', 'Western Europe', '... .. .. ..'),
  c('Belize', 'bz', 'blz', '501', 'Americas', 'Central America', '... ....'),
  c('Benin', 'bj', 'ben', '229', 'Africa', 'Western Africa', '.. .. ....'),
  c('Bhutan', 'bt', 'btn', '975', 'Asia', 'Southern Asia', '. ... ....'),
  c('Bolivia', 'bo', 'bol', '591', 'Americas', 'South America', '. .......'),
  c('Bosnia and Herzegovina', 'ba', 'bih', '387', 'Europe', 'Southern Europe', '.. ......'),
  c('Botswana', 'bw', 'bwa', '267', 'Africa', 'Southern Africa', '.. ... ...'),
  c('Brazil', 'br', 'bra', '55', 'Americas', 'South America', '.. .........'),
  c('Brunei', 'bn', 'brn', '673', 'Asia', 'South-Eastern Asia', '... ....'),
  c('Bulgaria', 'bg', 'bgr', '359', 'Europe', 'Eastern Europe', '... ... ...'),
  c('Burkina Faso', 'bf', 'bfa', '226', 'Africa', 'Western Africa', '.. .. .. ..'),
  c('Burundi', 'bi', 'bdi', '257', 'Africa', 'Eastern Africa', '.. .. .. ..'),
  c('Cambodia', 'kh', 'khm', '855', 'Asia', 'South-Eastern Asia', '.. ... ...'),
  c('Cameroon', 'cm', 'cmr', '237', 'Africa', 'Middle Africa', '.... ....'),
  c('Canada', 'ca', 'can', '1', 'Americas', 'Northern America', '... ... ....', 1, [
    '204',
    '226',
    '236',
    '249',
    '250',
    '263',
    '289',
    '306',
    '343',
    '354',
    '365',
    '367',
    '368',
    '382',
    '387',
    '403',
    '416',
    '418',
    '431',
    '437',
    '438',
    '450',
    '468',
    '474',
    '506',
    '514',
    '519',
    '548',
    '579',
    '581',
    '584',
    '587',
    '604',
    '613',
    '639',
    '647',
    '672',
    '683',
    '705',
    '709',
    '742',
    '753',
    '778',
    '780',
    '782',
    '807',
    '819',
    '825',
    '867',
    '873',
    '879',
    '902',
    '905',
  ]),
  c('Cape Verde', 'cv', 'cpv', '238', 'Africa', 'Western Africa', '... .. ..'),
  c('Central African Republic', 'cf', 'caf', '236', 'Africa', 'Middle Africa', '.. .. .. ..'),
  c('Chad', 'td', 'tcd', '235', 'Africa', 'Middle Africa', '.. .. .. ..'),
  c('Chile', 'cl', 'chl', '56', 'Americas', 'South America', '. .... ....'),
  c('China', 'cn', 'chn', '86', 'Asia', 'Eastern Asia', '... .... ....'),
  c('Colombia', 'co', 'col', '57', 'Americas', 'South America', '... ... ....'),
  c('Comoros', 'km', 'com', '269', 'Africa', 'Eastern Africa', '... .. ..'),
  c('Congo', 'cg', 'cog', '242', 'Africa', 'Middle Africa', '.. ... ....'),
  c('Congo (DRC)', 'cd', 'cod', '243', 'Africa', 'Middle Africa', '.. ... ....'),
  c('Costa Rica', 'cr', 'cri', '506', 'Americas', 'Central America', '.... ....'),
  c('Croatia', 'hr', 'hrv', '385', 'Europe', 'Southern Europe', '.. ... ....'),
  c("Côte d'Ivoire", 'ci', 'civ', '225', 'Africa', 'Western Africa', '.. .. .. ..'),
  c('Cuba', 'cu', 'cub', '53', 'Americas', 'Caribbean', '. .......'),
  c('Cyprus', 'cy', 'cyp', '357', 'Europe', 'Southern Europe', '.. ......'),
  c('Czech Republic', 'cz', 'cze', '420', 'Europe', 'Central Europe', '... ... ...'),
  c('Denmark', 'dk', 'dnk', '45', 'Europe', 'Northern Europe', '.. .. .. ..'),
  c('Djibouti', 'dj', 'dji', '253', 'Africa', 'Eastern Africa', '.. .. .. ..'),
  c('Dominica', 'dm', 'dma', '1', 'Americas', 'Caribbean', '... ....', 2, ['767']),
  c('Dominican Republic', 'do', 'dom', '1', 'Americas', 'Caribbean', '... ....', 2, [
    '809',
    '829',
    '849',
  ]),
  c('Ecuador', 'ec', 'ecu', '593', 'Americas', 'South America', '.. ... ....'),
  c('Egypt', 'eg', 'egy', '20', 'Africa', 'Northern Africa', '... ... ....'),
  c('El Salvador', 'sv', 'slv', '503', 'Americas', 'Central America', '.... ....'),
  c('Equatorial Guinea', 'gq', 'gnq', '240', 'Africa', 'Middle Africa', '... ... ...'),
  c('Eritrea', 'er', 'eri', '291', 'Africa', 'Eastern Africa', '. ... ...'),
  c('Estonia', 'ee', 'est', '372', 'Europe', 'Northern Europe', '.... ......'),
  c('Eswatini', 'sz', 'swz', '268', 'Africa', 'Southern Africa', '.... ....'),
  c('Ethiopia', 'et', 'eth', '251', 'Africa', 'Eastern Africa', '.. ... ....'),
  c('Fiji', 'fj', 'fji', '679', 'Oceania', 'Melanesia', '... ....'),
  c('Finland', 'fi', 'fin', '358', 'Europe', 'Northern Europe', '.. ... .. ..'),
  c('France', 'fr', 'fra', '33', 'Europe', 'Western Europe', '. .. .. .. ..'),
  c('Gabon', 'ga', 'gab', '241', 'Africa', 'Middle Africa', '. .. .. ..'),
  c('Gambia', 'gm', 'gmb', '220', 'Africa', 'Western Africa', '... ....'),
  c('Georgia', 'ge', 'geo', '995', 'Asia', 'Western Asia', '... .. .. ..'),
  c('Germany', 'de', 'deu', '49', 'Europe', 'Western Europe', '.... .......'),
  c('Ghana', 'gh', 'gha', '233', 'Africa', 'Western Africa', '.. ... ....'),
  c('Greece', 'gr', 'grc', '30', 'Europe', 'Southern Europe', '... ... ....'),
  c('Grenada', 'gd', 'grd', '1', 'Americas', 'Caribbean', '... ....', 2, ['473']),
  c('Guatemala', 'gt', 'gtm', '502', 'Americas', 'Central America', '.... ....'),
  c('Guinea', 'gn', 'gin', '224', 'Africa', 'Western Africa', '... .. .. ..'),
  c('Guinea-Bissau', 'gw', 'gnb', '245', 'Africa', 'Western Africa', '... ....'),
  c('Guyana', 'gy', 'guy', '592', 'Americas', 'South America', '... ....'),
  c('Haiti', 'ht', 'hti', '509', 'Americas', 'Caribbean', '.... ....'),
  c('Honduras', 'hn', 'hnd', '504', 'Americas', 'Central America', '.... ....'),
  c('Hong Kong', 'hk', 'hkg', '852', 'Asia', 'Eastern Asia', '.... ....'),
  c('Hungary', 'hu', 'hun', '36', 'Europe', 'Central Europe', '.. ... ....'),
  c('Iceland', 'is', 'isl', '354', 'Europe', 'Northern Europe', '... ....'),
  c('India', 'in', 'ind', '91', 'Asia', 'Southern Asia', '..... .....'),
  c('Indonesia', 'id', 'idn', '62', 'Asia', 'South-Eastern Asia', '... ... ....'),
  c('Iran', 'ir', 'irn', '98', 'Asia', 'Southern Asia', '... ... ....'),
  c('Iraq', 'iq', 'irq', '964', 'Asia', 'Western Asia', '... ... ....'),
  c('Ireland', 'ie', 'irl', '353', 'Europe', 'Northern Europe', '.. ... ....'),
  c('Israel', 'il', 'isr', '972', 'Asia', 'Western Asia', '.. ... ....'),
  c('Italy', 'it', 'ita', '39', 'Europe', 'Southern Europe', '... .......'),
  c('Jamaica', 'jm', 'jam', '1', 'Americas', 'Caribbean', '... ....', 2, ['876', '658']),
  c('Japan', 'jp', 'jpn', '81', 'Asia', 'Eastern Asia', '.. .... ....'),
  c('Jordan', 'jo', 'jor', '962', 'Asia', 'Western Asia', '. .... ....'),
  c('Kazakhstan', 'kz', 'kaz', '7', 'Asia', 'Central Asia', '... ... .. ..', 1, [
    '310',
    '311',
    '312',
    '313',
    '315',
    '318',
    '321',
    '324',
    '325',
    '326',
    '327',
    '336',
    '7172',
  ]),
  c('Kenya', 'ke', 'ken', '254', 'Africa', 'Eastern Africa', '... ......'),
  c('Kiribati', 'ki', 'kir', '686', 'Oceania', 'Micronesia', '.... ....'),
  c('Kosovo', 'xk', 'xkx', '383', 'Europe', 'Southern Europe', '.. ... ...'),
  c('Kuwait', 'kw', 'kwt', '965', 'Asia', 'Western Asia', '.... ....'),
  c('Kyrgyzstan', 'kg', 'kgz', '996', 'Asia', 'Central Asia', '... ... ...'),
  c('Laos', 'la', 'lao', '856', 'Asia', 'South-Eastern Asia', '.. .. ... ...'),
  c('Latvia', 'lv', 'lva', '371', 'Europe', 'Northern Europe', '.. ... ...'),
  c('Lebanon', 'lb', 'lbn', '961', 'Asia', 'Western Asia', '.. ... ...'),
  c('Lesotho', 'ls', 'lso', '266', 'Africa', 'Southern Africa', '.... ....'),
  c('Liberia', 'lr', 'lbr', '231', 'Africa', 'Western Africa', '... ... ...'),
  c('Libya', 'ly', 'lby', '218', 'Africa', 'Northern Africa', '.. ... ....'),
  c('Liechtenstein', 'li', 'lie', '423', 'Europe', 'Western Europe', '... ... ...'),
  c('Lithuania', 'lt', 'ltu', '370', 'Europe', 'Northern Europe', '... .....'),
  c('Luxembourg', 'lu', 'lux', '352', 'Europe', 'Western Europe', '... ... ...'),
  c('Macao', 'mo', 'mac', '853', 'Asia', 'Eastern Asia', '.... ....'),
  c('Madagascar', 'mg', 'mdg', '261', 'Africa', 'Eastern Africa', '.. .. ... ..'),
  c('Malawi', 'mw', 'mwi', '265', 'Africa', 'Eastern Africa', '.... ......'),
  c('Malaysia', 'my', 'mys', '60', 'Asia', 'South-Eastern Asia', '.. .... ....'),
  c('Maldives', 'mv', 'mdv', '960', 'Asia', 'Southern Asia', '... ....'),
  c('Mali', 'ml', 'mli', '223', 'Africa', 'Western Africa', '.. .. .. ..'),
  c('Malta', 'mt', 'mlt', '356', 'Europe', 'Southern Europe', '.... ....'),
  c('Marshall Islands', 'mh', 'mhl', '692', 'Oceania', 'Micronesia', '... ....'),
  c('Mauritania', 'mr', 'mrt', '222', 'Africa', 'Western Africa', '.. .. .. ..'),
  c('Mauritius', 'mu', 'mus', '230', 'Africa', 'Eastern Africa', '.... ....'),
  c('Mexico', 'mx', 'mex', '52', 'Americas', 'Central America', '... ... ....'),
  c('Micronesia', 'fm', 'fsm', '691', 'Oceania', 'Micronesia', '... ....'),
  c('Moldova', 'md', 'mda', '373', 'Europe', 'Eastern Europe', '.... ....'),
  c('Monaco', 'mc', 'mco', '377', 'Europe', 'Western Europe', '.. .. .. ..'),
  c('Mongolia', 'mn', 'mng', '976', 'Asia', 'Eastern Asia', '.... ....'),
  c('Montenegro', 'me', 'mne', '382', 'Europe', 'Southern Europe', '.. ... ...'),
  c('Morocco', 'ma', 'mar', '212', 'Africa', 'Northern Africa', '.. .... ...'),
  c('Mozambique', 'mz', 'moz', '258', 'Africa', 'Eastern Africa', '.. ... ....'),
  c('Myanmar', 'mm', 'mmr', '95', 'Asia', 'South-Eastern Asia', '... ... ...'),
  c('Namibia', 'na', 'nam', '264', 'Africa', 'Southern Africa', '.. ... ....'),
  c('Nauru', 'nr', 'nru', '674', 'Oceania', 'Micronesia', '... ....'),
  c('Nepal', 'np', 'npl', '977', 'Asia', 'Southern Asia', '... ... ....'),
  c('Netherlands', 'nl', 'nld', '31', 'Europe', 'Western Europe', '. .. .. .. ..'),
  c('New Zealand', 'nz', 'nzl', '64', 'Oceania', 'Australia and New Zealand', '... ... ....'),
  c('Nicaragua', 'ni', 'nic', '505', 'Americas', 'Central America', '.... ....'),
  c('Niger', 'ne', 'ner', '227', 'Africa', 'Western Africa', '.. .. .. ..'),
  c('Nigeria', 'ng', 'nga', '234', 'Africa', 'Western Africa', '... ... ....'),
  c('North Korea', 'kp', 'prk', '850', 'Asia', 'Eastern Asia', '... ... ....'),
  c('North Macedonia', 'mk', 'mkd', '389', 'Europe', 'Southern Europe', '.. ... ...'),
  c('Norway', 'no', 'nor', '47', 'Europe', 'Northern Europe', '... .. ...'),
  c('Oman', 'om', 'omn', '968', 'Asia', 'Western Asia', '.... ....'),
  c('Pakistan', 'pk', 'pak', '92', 'Asia', 'Southern Asia', '... .......'),
  c('Palau', 'pw', 'plw', '680', 'Oceania', 'Micronesia', '... ....'),
  c('Palestine', 'ps', 'pse', '970', 'Asia', 'Western Asia', '... ... ...'),
  c('Panama', 'pa', 'pan', '507', 'Americas', 'Central America', '.... ....'),
  c('Papua New Guinea', 'pg', 'png', '675', 'Oceania', 'Melanesia', '... .. ...'),
  c('Paraguay', 'py', 'pry', '595', 'Americas', 'South America', '... ......'),
  c('Peru', 'pe', 'per', '51', 'Americas', 'South America', '... ... ...'),
  c('Philippines', 'ph', 'phl', '63', 'Asia', 'South-Eastern Asia', '... ... ....'),
  c('Poland', 'pl', 'pol', '48', 'Europe', 'Central Europe', '... ... ...'),
  c('Portugal', 'pt', 'prt', '351', 'Europe', 'Southern Europe', '... ... ...'),
  c('Puerto Rico', 'pr', 'pri', '1', 'Americas', 'Caribbean', '... ....', 2, ['787', '939']),
  c('Qatar', 'qa', 'qat', '974', 'Asia', 'Western Asia', '.... ....'),
  c('Romania', 'ro', 'rou', '40', 'Europe', 'Eastern Europe', '... ... ...'),
  c('Russia', 'ru', 'rus', '7', 'Europe', 'Eastern Europe', '... ... .. ..', 0),
  c('Rwanda', 'rw', 'rwa', '250', 'Africa', 'Eastern Africa', '... ... ...'),
  c('Saint Kitts and Nevis', 'kn', 'kna', '1', 'Americas', 'Caribbean', '... ....', 2, ['869']),
  c('Saint Lucia', 'lc', 'lca', '1', 'Americas', 'Caribbean', '... ....', 2, ['758']),
  c('Saint Vincent and the Grenadines', 'vc', 'vct', '1', 'Americas', 'Caribbean', '... ....', 2, [
    '784',
  ]),
  c('Samoa', 'ws', 'wsm', '685', 'Oceania', 'Polynesia', '.. ....'),
  c('San Marino', 'sm', 'smr', '378', 'Europe', 'Southern Europe', '.... ......'),
  c('São Tomé and Príncipe', 'st', 'stp', '239', 'Africa', 'Middle Africa', '... ....'),
  c('Saudi Arabia', 'sa', 'sau', '966', 'Asia', 'Western Asia', '.. ... ....'),
  c('Senegal', 'sn', 'sen', '221', 'Africa', 'Western Africa', '.. ... .. ..'),
  c('Serbia', 'rs', 'srb', '381', 'Europe', 'Southern Europe', '.. ... ....'),
  c('Seychelles', 'sc', 'syc', '248', 'Africa', 'Eastern Africa', '. ... ...'),
  c('Sierra Leone', 'sl', 'sle', '232', 'Africa', 'Western Africa', '.. ......'),
  c('Singapore', 'sg', 'sgp', '65', 'Asia', 'South-Eastern Asia', '.... ....'),
  c('Slovakia', 'sk', 'svk', '421', 'Europe', 'Central Europe', '... ... ...'),
  c('Slovenia', 'si', 'svn', '386', 'Europe', 'Southern Europe', '.. ... ...'),
  c('Solomon Islands', 'sb', 'slb', '677', 'Oceania', 'Melanesia', '... ....'),
  c('Somalia', 'so', 'som', '252', 'Africa', 'Eastern Africa', '.. .......'),
  c('South Africa', 'za', 'zaf', '27', 'Africa', 'Southern Africa', '.. ... ....'),
  c('South Korea', 'kr', 'kor', '82', 'Asia', 'Eastern Asia', '.. .... ....'),
  c('South Sudan', 'ss', 'ssd', '211', 'Africa', 'Eastern Africa', '.. ... ....'),
  c('Spain', 'es', 'esp', '34', 'Europe', 'Southern Europe', '... .. .. ..'),
  c('Sri Lanka', 'lk', 'lka', '94', 'Asia', 'Southern Asia', '.. ... ....'),
  c('Sudan', 'sd', 'sdn', '249', 'Africa', 'Northern Africa', '.. ... ....'),
  c('Suriname', 'sr', 'sur', '597', 'Americas', 'South America', '... ....'),
  c('Sweden', 'se', 'swe', '46', 'Europe', 'Northern Europe', '.. ... .. ..'),
  c('Switzerland', 'ch', 'che', '41', 'Europe', 'Western Europe', '.. ... .. ..'),
  c('Syria', 'sy', 'syr', '963', 'Asia', 'Western Asia', '... ... ...'),
  c('Taiwan', 'tw', 'twn', '886', 'Asia', 'Eastern Asia', '... ... ...'),
  c('Tajikistan', 'tj', 'tjk', '992', 'Asia', 'Central Asia', '.. ... ....'),
  c('Tanzania', 'tz', 'tza', '255', 'Africa', 'Eastern Africa', '.. ... ....'),
  c('Thailand', 'th', 'tha', '66', 'Asia', 'South-Eastern Asia', '.. .... ....'),
  c('Timor-Leste', 'tl', 'tls', '670', 'Asia', 'South-Eastern Asia', '.... ....'),
  c('Togo', 'tg', 'tgo', '228', 'Africa', 'Western Africa', '.. .. .. ..'),
  c('Tonga', 'to', 'ton', '676', 'Oceania', 'Polynesia', '... ....'),
  c('Trinidad and Tobago', 'tt', 'tto', '1', 'Americas', 'Caribbean', '... ....', 2, ['868']),
  c('Tunisia', 'tn', 'tun', '216', 'Africa', 'Northern Africa', '.. ... ...'),
  c('Turkey', 'tr', 'tur', '90', 'Asia', 'Western Asia', '... ... .. ..'),
  c('Turkmenistan', 'tm', 'tkm', '993', 'Asia', 'Central Asia', '.. .. .. ..'),
  c('Tuvalu', 'tv', 'tuv', '688', 'Oceania', 'Polynesia', '.. ....'),
  c('Uganda', 'ug', 'uga', '256', 'Africa', 'Eastern Africa', '... ......'),
  c('Ukraine', 'ua', 'ukr', '380', 'Europe', 'Eastern Europe', '.. ... .. ..'),
  c('United Arab Emirates', 'ae', 'are', '971', 'Asia', 'Western Asia', '.. ... ....'),
  c('United Kingdom', 'gb', 'gbr', '44', 'Europe', 'Northern Europe', '.... ......'),
  c('United States', 'us', 'usa', '1', 'Americas', 'Northern America', '... ... ....', 0, [
    '201',
    '202',
    '203',
    '205',
    '206',
    '207',
    '208',
    '209',
    '210',
    '212',
    '213',
    '214',
    '215',
    '216',
    '217',
    '218',
    '219',
    '220',
    '223',
    '224',
    '225',
    '228',
    '229',
    '231',
    '234',
    '239',
    '240',
    '248',
    '251',
    '252',
    '253',
    '254',
    '256',
    '260',
    '262',
    '267',
    '269',
    '270',
    '272',
    '274',
    '276',
    '279',
    '281',
    '283',
    '301',
    '302',
    '303',
    '304',
    '305',
    '307',
    '308',
    '309',
    '310',
    '312',
    '313',
    '314',
    '315',
    '316',
    '317',
    '318',
    '319',
    '320',
    '321',
    '323',
    '325',
    '326',
    '327',
    '330',
    '331',
    '332',
    '334',
    '336',
    '337',
    '339',
    '340',
    '346',
    '347',
    '351',
    '352',
    '360',
    '361',
    '364',
    '380',
    '385',
    '386',
    '401',
    '402',
    '404',
    '405',
    '406',
    '407',
    '408',
    '409',
    '410',
    '412',
    '413',
    '414',
    '415',
    '417',
    '419',
    '423',
    '424',
    '425',
    '430',
    '432',
    '434',
    '435',
    '440',
    '442',
    '443',
    '445',
    '447',
    '448',
    '458',
    '463',
    '464',
    '469',
    '470',
    '475',
    '478',
    '479',
    '480',
    '484',
    '501',
    '502',
    '503',
    '504',
    '505',
    '507',
    '508',
    '509',
    '510',
    '512',
    '513',
    '515',
    '516',
    '517',
    '518',
    '520',
    '530',
    '531',
    '534',
    '539',
    '540',
    '541',
    '551',
    '559',
    '561',
    '562',
    '563',
    '564',
    '567',
    '570',
    '571',
    '572',
    '573',
    '574',
    '575',
    '580',
    '585',
    '586',
    '601',
    '602',
    '603',
    '605',
    '606',
    '607',
    '608',
    '609',
    '610',
    '612',
    '614',
    '615',
    '616',
    '617',
    '618',
    '619',
    '620',
    '623',
    '626',
    '628',
    '629',
    '630',
    '631',
    '636',
    '641',
    '646',
    '650',
    '651',
    '657',
    '659',
    '660',
    '661',
    '662',
    '667',
    '669',
    '678',
    '680',
    '681',
    '682',
    '689',
    '701',
    '702',
    '703',
    '704',
    '706',
    '707',
    '708',
    '712',
    '713',
    '714',
    '715',
    '716',
    '717',
    '718',
    '719',
    '720',
    '724',
    '725',
    '726',
    '727',
    '731',
    '732',
    '734',
    '737',
    '740',
    '743',
    '747',
    '754',
    '757',
    '760',
    '762',
    '763',
    '765',
    '769',
    '770',
    '772',
    '773',
    '774',
    '775',
    '779',
    '781',
    '785',
    '786',
    '801',
    '802',
    '803',
    '804',
    '805',
    '806',
    '808',
    '810',
    '812',
    '813',
    '814',
    '815',
    '816',
    '817',
    '818',
    '820',
    '828',
    '830',
    '831',
    '832',
    '835',
    '838',
    '839',
    '840',
    '843',
    '845',
    '847',
    '848',
    '850',
    '854',
    '856',
    '857',
    '858',
    '859',
    '860',
    '862',
    '863',
    '864',
    '865',
    '870',
    '872',
    '878',
    '901',
    '903',
    '904',
    '906',
    '907',
    '908',
    '909',
    '910',
    '912',
    '913',
    '914',
    '915',
    '916',
    '917',
    '918',
    '919',
    '920',
    '925',
    '928',
    '929',
    '930',
    '931',
    '934',
    '936',
    '937',
    '938',
    '940',
    '941',
    '943',
    '945',
    '947',
    '949',
    '951',
    '952',
    '954',
    '956',
    '959',
    '970',
    '971',
    '972',
    '973',
    '975',
    '978',
    '979',
    '980',
    '984',
    '985',
    '986',
    '989',
  ]),
  c('Uruguay', 'uy', 'ury', '598', 'Americas', 'South America', '. ... .. ..'),
  c('Uzbekistan', 'uz', 'uzb', '998', 'Asia', 'Central Asia', '.. ... ....'),
  c('Vanuatu', 'vu', 'vut', '678', 'Oceania', 'Melanesia', '... ....'),
  c('Vatican City', 'va', 'vat', '39', 'Europe', 'Southern Europe', '.. .... ....', 1),
  c('Venezuela', 've', 'ven', '58', 'Americas', 'South America', '... ... ....'),
  c('Vietnam', 'vn', 'vnm', '84', 'Asia', 'South-Eastern Asia', '.. .... ....'),
  c('Yemen', 'ye', 'yem', '967', 'Asia', 'Western Asia', '... ... ...'),
  c('Zambia', 'zm', 'zmb', '260', 'Africa', 'Eastern Africa', '.. .......'),
  c('Zimbabwe', 'zw', 'zwe', '263', 'Africa', 'Eastern Africa', '.. ... ....'),
];

/**
 * Top 50 most-used countries for lightweight builds.
 */
export const countriesMinimal: Country[] = countries.filter((country) =>
  [
    'us',
    'gb',
    'ca',
    'au',
    'de',
    'fr',
    'es',
    'it',
    'br',
    'mx',
    'in',
    'cn',
    'jp',
    'kr',
    'ru',
    'nl',
    'be',
    'ch',
    'at',
    'se',
    'no',
    'dk',
    'fi',
    'pl',
    'cz',
    'pt',
    'ie',
    'nz',
    'za',
    'ar',
    'co',
    'cl',
    'pe',
    've',
    'ec',
    'tr',
    'sa',
    'ae',
    'il',
    'eg',
    'ng',
    'ke',
    'ph',
    'th',
    'id',
    'my',
    'sg',
    'hk',
    'tw',
    'pk',
  ].includes(country.iso2),
);

/**
 * Find a country by ISO2 code.
 */
export function getCountryByIso2(iso2: string): Country | undefined {
  return countries.find((c) => c.iso2 === iso2.toLowerCase());
}

/**
 * Find a country by ISO3 code.
 */
export function getCountryByIso3(iso3: string): Country | undefined {
  return countries.find((c) => c.iso3 === iso3.toLowerCase());
}

/**
 * Find countries by dial code. Returns multiple for shared codes (e.g., +1).
 */
export function getCountriesByDialCode(dialCode: string): Country[] {
  return countries.filter((c) => c.dialCode === dialCode);
}
